- hosts: localhost
  gather_facts: false
  become: true
  remote_user: armin
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include_tasks: tasks/core-setup.yml
    # - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/composer-setup.yml
    - include_tasks: tasks/node-npm.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/productivity-tools.yml
    - include_tasks: tasks/php-setup.yml
    - include_tasks: tasks/nvim-setup.yml
    - include_tasks: tasks/thorium.yml
