- name: Download Composer installer
  shell: cd ~ && curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
  args:
    creates: /tmp/composer-setup.php

- name: Install Composer
  shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
