- name: Install System Packages 1 (build-essential, cmake, pkg-config, procps)
  apt:
    name: ["build-essential", "cmake", "pkg-config", "procps"]
  tags:
    - install
    - neovim
    - core
- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  apt:
    name: ["unzip", "libtool", "libtool-bin", "gettext", "php-cli"]
  tags:
    - install
    - neovim
    - core
- name: Install System Packages 3 (the rest)
  apt: name={{item}}
  with_items:
    - curl
    - htop
    - lsof
    - file
    - git
    - python3-pip
  tags:
    - install
    - core
