- name: Install nodejs and (p)npm
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - node
- name: Install Node 18 lts
  shell: n 18
  tags:
    - install
    - node

- name: Install pnpm
  npm:
    name: pnpm
    global: yes
  tags:
    - install
    - node
