- name: Install ZSH
  apt: name=zsh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Install Zoxide
  shell: "curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash"
- name: Add zoxide initialization to zshrc
  lineinfile:
    path: ~/.zshrc
    line: 'eval "$(zoxide init zsh)"'
    insertafter: EOF
  become: yes
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
