- name: Install ZSH
  apt: name=zsh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Install Zoxide
  shell: "curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash"
  become: yes
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Add zoxide initialization to zshrc
  lineinfile:
    path: /home/armin/.zshrc
    line: 'eval "$(zoxide init zsh)"'
    insertafter: EOF
    state: present
  become: yes
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
